apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
  labels:
    run: movie-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: movie-catalog-service
  template:
    metadata:
      labels:
        run: movie-catalog-service
    spec:
      containers:
      - name: movie-catalog-service
        image: roumilsharma/movie-catalog-service:v1
        ports:
        - containerPort: 8081